### ISSUE TITLE
Video pauses for milli second before looping again

### ISSUE THREAD

**Issue by msushanktheglitch** [horsepress/videoJsABLoopPlugin#1]
Hi,
When i was viewing https://cdn.rawgit.com/phhu/videojs-abloop/master/sample/basic.html link on my desktop it works perfectly fine, but when I viewed this link on an Android phone browser(chrome), just before the video loops back, there is a small lag for may be half a second. While looping back it gets stuck on 15th second for half a second and then loops back. This keeps happening every time the video loops. With a looping video it is very noticeable. Please somebody, please let me know a solution for this.

**Comment by phhu** [comment]
Not sure of cause. Possibly a caching issue: the player wouldn't expect the loop back, and so might not have data cached to play it, hence the brief pause while it downloads (again). Mobile devices might be more prone to this (memory / network limitations??). 

There might be a means of warning the browser of the impending loop, so that it can request in advance? Or possibly to (manually) cache the segment after the loop start, so that it is always available? (see e.g. https://developers.google.com/web/fundamentals/media/mse/basics )

Might be worth experimenting with different video file sizes, browsers, versions etc.

**Comment by phhu** [comment]
A possible solution is to use a blob as the video src: load the video via ajax / fetch, then convert to a blob and set the blob as the src. 

See example at sample/blob.html

It works on desktop. I've not tested on android, as I don't have a suitable phone. 

```js
//See https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch 

var video = videojs("vid",{
	plugins: {
		abLoopPlugin: {}
	}
});

fetch('oceans.mp4')     // or use https://vjs.zencdn.net/v/oceans.mp4
	.then((res) => {
		if (!res.ok) {
			throw new Error('Network response was not ok');
		}
		return res.blob();
	})
	.then((blob) => {
		video.src({
			src: URL.createObjectURL(blob),
			type: "video/mp4" 
		});
		video.ready(function(){
			this.abLoopPlugin.setStart(10).setEnd(11).playLoop();
		});
	})
	.catch((error) => {
		console.error('There has been a problem with your fetch operation:', error);
	});
```

**Comment by phhu** [comment]
...likely a caching issue, which is out of scope for this plugin - but see above for possible solution.
