### ISSUE TITLE
loopIfBeforeStart:false not working

### ISSUE THREAD

**Issue by cloudstudio** [horsepress/videoJsABLoopPlugin#9]
Hello @phhu ! thanks in advance.

I want to reproduce video normally, and start bucle for example in second 30 to 40.

When I load the page, by default start in 30, maybe is something wrong with loopIfBeforeStart ? true / false, nothing happend.

I need use setTimeout for work with, something weird...

Thanks man!

```

const player = videojs('vid', {
    controls: false,
    autoplay: true,
    plugins: {
        abLoopPlugin: {
            start: 0,
            enabled: false,
            loopIfBeforeStart: false,
            createButtons: true
        }
    }
});


setTimeout(function () {
    console.log("setting new start and end...");
    player.abLoopPlugin.setStart(30).setEnd(40).enable();
}, 30000);
```

**Comment by phhu** [comment]
I'm guessing you worked this out, since it's closed. Let me know if not.

If you're trying to play the video from the start, then when it reaches 40s, loop back to 30s and keep looping 30s to 40s thereafter, I think something like this would work:

```
const player = videojs('vid', {
    controls: false,
    autoplay: true,
    plugins: {
        abLoopPlugin: {
            start: 30,
            end: 40,
            enabled: true,
            loopIfBeforeStart: false,
            createButtons: true
        }
    }
});
player.play();
```

This would still mean that, if the video is moved to somewhere before 30s after the loop has happened, it would not loop (back to 30s) until the video is after 40s again.

(Rather than using timeouts, you can use the callbacks to change settings after loops: e.g. here you might set loopIfBeforeStart to true once the loop happens to make it then bounce to the loop section).
```
